# Linear Algebra Tutorial Using Python

Linear algebra is a foundational area of mathematics, crucial for understanding data science, machine learning, computer graphics, and more. In this tutorial, we’ll explore the concept of **Basis** in linear algebra, using Python (with NumPy) for hands-on examples.

---

## Prerequisites

- Python 3.x installed
- [NumPy](https://numpy.org/) library installed

You can install NumPy using pip:
```bash
pip install numpy
```

---

## What is a Basis?

A **basis** of a vector space is a set of linearly independent vectors that span the entire space. Every vector in the space can be written as a linear combination of the basis vectors.

**Key Points:**
- **Linearly Independent**: No vector in the set can be written as a combination of the others.
- **Span**: Any vector in the space can be formed by a combination of the basis vectors.

---

## Example 1: Standard Basis in 2D

The standard basis for $\mathbb{R}^2$ (the 2D plane) is:
$$
\mathbf{e}_1 = \begin{bmatrix}1 \\ 0\end{bmatrix},\quad \mathbf{e}_2 = \begin{bmatrix}0 \\ 1\end{bmatrix}
$$

In [1]:
import numpy as np

# Standard basis vectors in R^2
e1 = np.array([1, 0])
e2 = np.array([0, 1])

print("e1:", e1)
print("e2:", e2)

e1: [1 0]
e2: [0 1]


## Example 2: Checking Linear Independence

Let’s check if two vectors are linearly independent using NumPy:

In [2]:
# Define two vectors
v1 = np.array([2, 3])
v2 = np.array([1, 4])

# Stack the vectors as columns in a matrix
A = np.column_stack([v1, v2])

# Compute the rank
rank = np.linalg.matrix_rank(A)

print("Matrix:\n", A)
print("Rank:", rank)

if rank == 2:
    print("The vectors are linearly independent.")
else:
    print("The vectors are linearly dependent.")

Matrix:
 [[2 1]
 [3 4]]
Rank: 2
The vectors are linearly independent.


## Example 3: Spanning a Vector

Suppose you want to represent the vector $ \mathbf{v} = [5, 7] $ as a combination of the basis vectors $v_1 = [2, 3]$ and $v_2 = [1, 4]$:

Solve for scalars $a$ and $b$ such that:
$$
a \cdot v_1 + b \cdot v_2 = v
$$

In [3]:
v = np.array([5, 7])
V = np.column_stack([v1, v2])

# Solve V * [a, b] = v
coefficients = np.linalg.solve(V, v)
print("Coefficients:", coefficients)
print(f"{coefficients[0]} * v1 + {coefficients[1]} * v2 = {v}")

Coefficients: [ 2.6 -0.2]
2.6000000000000005 * v1 + -0.20000000000000037 * v2 = [5 7]


## Example 4: Basis in Higher Dimensions

For $\mathbb{R}^3$:

In [4]:
e1 = np.array([1, 0, 0])
e2 = np.array([0, 1, 0])
e3 = np.array([0, 0, 1])

basis = [e1, e2, e3]
print("Standard basis for R^3:")
for v in basis:
    print(v)

Standard basis for R^3:
[1 0 0]
[0 1 0]
[0 0 1]


## Practice

- Try defining your own set of vectors in $\mathbb{R}^2$ or $\mathbb{R}^3$.
- Check if your set forms a basis by:
  1. Verifying linear independence (`np.linalg.matrix_rank`)
  2. Ensuring the set can span the space

---

## Summary

- A **basis** is a set of linearly independent vectors that span a vector space.
- In Python, use NumPy to check independence and solve linear combinations.
- Understanding basis is fundamental for more advanced topics in linear algebra.

**Happy coding!**

# [Linear Algebra Context](./README.md)