# Linear Algebra with Python: Matrices

Matrices are fundamental building blocks in linear algebra. They are used to represent linear transformations, systems of equations, and more. In this tutorial, you'll learn how to work with matrices using Python.

---

## 1. What is a Matrix?

- **Definition**: A matrix is a rectangular array of numbers arranged in rows and columns.
- **Example**:  
  $$
  A = \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6
  \end{bmatrix}
  $$
  This is a 2x3 matrix (2 rows, 3 columns).

---

## 2. Creating Matrices in Python

We'll use the `numpy` library, which is powerful for numerical computations.

In [1]:
import numpy as np

# Create a 2x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Matrix A:\n", A)

# Create a 3x3 identity matrix
I = np.eye(3)
print("Identity Matrix:\n", I)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 3. Matrix Operations

### a. Addition and Subtraction

You can add or subtract matrices of the same shape.

In [2]:
B = np.array([[7, 8, 9],
              [10, 11, 12]])
C = A + B
print("A + B:\n", C)

A + B:
 [[ 8 10 12]
 [14 16 18]]


### b. Scalar Multiplication

In [3]:
scalar = 2
D = scalar * A
print("2 * A:\n", D)

2 * A:
 [[ 2  4  6]
 [ 8 10 12]]


### c. Matrix Multiplication

For two matrices $ A $ (of shape $ m \times n $) and $ B $ (of shape $ n \times p $), their product is an $ m \times p $ matrix.


In [4]:
# Matrix multiplication (dot product)
E = np.array([[1, 2],
              [3, 4],
              [5, 6]])
product = np.dot(A, E)
print("A dot E:\n", product)

A dot E:
 [[22 28]
 [49 64]]


Or, with the `@` operator (Python 3.5+):

In [6]:
product2 = A @ E
print("A dot E:\n", product2)

A dot E:
 [[22 28]
 [49 64]]


## 4. Transpose of a Matrix

The transpose flips a matrix over its diagonal.


In [7]:
A_T = A.T
print("Transpose of A:\n", A_T)

Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]


## 5. Inverse of a Matrix

Only square matrices (same number of rows and columns) with non-zero determinant have inverses.

In [8]:
F = np.array([[1, 2],
              [3, 4]])
F_inv = np.linalg.inv(F)
print("Inverse of F:\n", F_inv)

Inverse of F:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## 6. Determinant of a Matrix

The determinant is a special number that can be calculated from a square matrix.

In [9]:
det_F = np.linalg.det(F)
print("Determinant of F:", det_F)

Determinant of F: -2.0000000000000004


## 7. Solving Systems of Linear Equations

Suppose you have the system:
$$
2x + y = 5     
$$
$$
x - y = 1
$$
This can be written as $ AX = B $:

$$
A = \begin{bmatrix} 2 & 1 \\ 1 & -1 \end{bmatrix},\quad X = \begin{bmatrix} x \\ y \end{bmatrix},\quad B = \begin{bmatrix} 5 \\ 1 \end{bmatrix}
$$

You can solve for $ X $ using:

In [10]:
A_sys = np.array([[2, 1], [1, -1]])
B_sys = np.array([5, 1])
X = np.linalg.solve(A_sys, B_sys)
print("Solution [x, y]:", X)

Solution [x, y]: [2. 1.]


## 8. Linear Transformations

Matrices can represent transformations like rotations, scaling, and shearing in space.

### Example: 2D Rotation

$$
R(\theta) = \begin{bmatrix}
\cos\theta & -\sin\theta \\
\sin\theta & \cos\theta
\end{bmatrix}
$$

Rotate vector $ v = [1, 0] $ by 90 degrees:

In [11]:
theta = np.deg2rad(90)
R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])
v = np.array([1, 0])
v_rotated = R @ v
print("Rotated vector:", v_rotated)

Rotated vector: [6.123234e-17 1.000000e+00]


## 9. Applications

- **Computer Graphics:** Transforming coordinates, scaling, rotating images.
- **Physics/Engineering:** Solving systems (e.g., circuits, forces).
- **Data Science:** Encoding data, performing principal component analysis (PCA).

---

## 10. Summary

- Matrices are rectangular arrays used to represent linear transformations and solve equations.
- Python's `numpy` library makes matrix operations efficient and easy.
- Key operations: addition, multiplication, transpose, inverse, determinant, and solving systems.

---

**Explore more:**  
- [NumPy Linear Algebra Documentation](https://numpy.org/doc/stable/reference/routines.linalg.html)  
- [3Blue1Brown: Essence of Linear Algebra (YouTube)](https://www.youtube.com/watch?v=kjBOesZCoqc)

---

# [Linear Algebra Context](./README.md)